name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: List files
      run: ls -R

    - name: Build Backend Image
      run: |
        docker build -t stock-prediction-backend:latest -f backend/Dockerfile .

    - name: Build Frontend Image
      run: |
        docker build -t stock-price-frontiers:latest -f frontend/Dockerfile .